
ch01_matlab.pdf: 01.Numbers/ch01.tex
	pdflatex -jobname ch01_matlab 01.Numbers/ch01.tex

ch01_python.pdf: ch01.tex
	pdflatex -jobname ch01_python 01.Numbers/ch01.tex
 
clean:
	rm -f 01.Numbers/ch01_matlab.pdf 01.Numbers/ch01_python.pdf
